name: Deploy Flask app

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, run]

    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Deploy
        run: docker compose up -d --build