# This workflow is triggered when a new release is published. It deploys the application to the server using SSH.
name: Deploy to server
on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: installting  docker compose file to the server
              uses: appleboy/ssh-action@v0.1.0
              with:
                host: ${{ secrets.SERVER_EC2_DEPLOYMENT_HOST }}
                username: ${{ secrets.SERVER_EC2_USER}}
                key: ${{ secrets.SERVER_EC2_SSH_KEY}}
                source: "docker-compose.yml"
                target: "~/devops-joosh/docker-compose.yml"
                run: |
                    echo "installing required dependencies and creating necessary directories on the server..."
                    mkdir -p ~/devops-joosh
                    cd ~/devops-joosh && scp docker-compose.yml ${{ secrets.SERVER_EC2_USER}}@${{ secrets.SERVER_EC2_DEPLOYMENT_HOST }}:~/devops-joosh/docker-compose.yml
                    sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
                    sudo usermod -aG docker $USER && newgrp docker

            - name: Run the application on the server
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.SERVER_EC2_DEPLOYMENT_HOST }}
                username: ${{ secrets.SERVER_EC2_USER}}
                key: ${{ secrets.SERVER_EC2_SSH_KEY}}
                script: |
                  echo "Running the application...."
                  echo "installing required dependencies and creating necessary directories on the server..."
                  mkdir -p ~/devops-joosh
                  sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
                  sudo usermod -aG docker $USER && newgrp docker
                  export DOCKER_USERNAME=${{ vars.DOCKER_USERNAME }}
                  export DOCKER_TAG=${{github.event.workflow_run.head_sha}}
                  echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{vars.DOCKER_USERNAME}} --password-stdin
                  cd devops-joosh && docker compose down && docker compose up -d --build --force-recreate --pull always