# This workflow is triggered when a new release is published. It deploys the application to the server using SSH.
name: Deploy to server
on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: SSH to Pro Server and Deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SERVER_EC2_HOST }}
                username: ${{ secrets.SERVER__EC2_USER }}
                key: ${{ secrets.SERVER_EC2_SSH_KEY }}
                script: |
                  echo "Starting Deployment...."
                  mkdir -p devops-joosh