# This workflow is triggered on push to the main branch and pull requests targeting the main branch.
name : DevSecops
on:
    push:
        branches: [main]

jobs:
    code-quality-deploy:
        uses: ./.github/workflows/code_Quality.yml

    secret-scan:
        uses: ./.github/workflows/secret_scan.yml

    dependency-scan:
        uses: ./.github/workflows/dependency_check.yml

    Docker-image-scan:
        uses: ./.github/workflows/image-scan.yml